spring:
  data:
    redis:
      host: redis://default:TARNJcteVwVobRXFeNCCOd2AfuvAr428@redis-12584.crce179.ap-south-1-1.ec2.cloud.redislabs.com:12584
      port: 12584
      password: redis-12584.crce179.ap-south-1-1.ec2.cloud.redislabs.com
    mongodb:
      uri: mongodb+srv://piyushahuja575_db_user:Piyu%4008@mydb.bk98xti.mongodb.net/?appName=Mydb
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: piyushahuja575@gmail.com
    password: nzkk zypa dznb idir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080

weather:
  api:
    key: 63e8d5347951a7b959f97c7d8c9d436f
